"""Add stock_actual and stock_minimo to Producto model

Revision ID: 1e293762ddc2
Revises: 26d6b0cc9b2e
Create Date: 2025-07-03 17:59:16.777911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e293762ddc2'
down_revision: Union[str, Sequence[str], None] = '26d6b0cc9b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock_actual', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('productos', sa.Column('stock_minimo', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('productos', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('productos', 'stock_minimo')
    op.drop_column('productos', 'stock_actual')
    # ### end Alembic commands ###
