"""Add Gasto model

Revision ID: 26d6b0cc9b2e
Revises: 125033847437
Create Date: 2025-07-03 17:24:14.226086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d6b0cc9b2e'
down_revision: Union[str, Sequence[str], None] = '125033847437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_categoria'), 'gastos', ['categoria'], unique=False)
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_categoria'), table_name='gastos')
    op.drop_table('gastos')
    # ### end Alembic commands ###
